/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorInformacion;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.LineaInvestigacion;

/**
 *
 * @author mario
 */
public class V_LineaInvestigacion extends javax.swing.JFrame {
    
    ControladorInformacion control = new ControladorInformacion();

    /**
     * Creates new form V_LineaInvestigacion
     */
    public V_LineaInvestigacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idCrear = new javax.swing.JFormattedTextField();
        nomCrear = new javax.swing.JFormattedTextField();
        jBotonCrear = new javax.swing.JButton();
        fondo1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        buscarRead = new javax.swing.JFormattedTextField();
        busRead = new javax.swing.JButton();
        cedula = new javax.swing.JLabel();
        celular = new javax.swing.JLabel();
        idRead = new javax.swing.JTextField();
        nomRead = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cedula1 = new javax.swing.JLabel();
        celular1 = new javax.swing.JLabel();
        idUpdate = new javax.swing.JTextField();
        nomUpdate = new javax.swing.JTextField();
        titulo1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        buscarUpdate = new javax.swing.JFormattedTextField();
        busUpdate = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        fondo3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cedula2 = new javax.swing.JLabel();
        celular2 = new javax.swing.JLabel();
        idDelete = new javax.swing.JTextField();
        nomDelete = new javax.swing.JTextField();
        titulo2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        buscarDelete = new javax.swing.JFormattedTextField();
        busDelete = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        fondo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRUD linea de investigacion");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setText("Id (*)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setText("Nombre de la línea de investigación (*)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        idCrear.setEditable(false);
        idCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCrearActionPerformed(evt);
            }
        });
        idCrear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idCrearKeyTyped(evt);
            }
        });
        jPanel1.add(idCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 248, 35));

        nomCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomCrearActionPerformed(evt);
            }
        });
        jPanel1.add(nomCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 248, 35));

        jBotonCrear.setText("Crear");
        jBotonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonCrearActionPerformed(evt);
            }
        });
        jPanel1.add(jBotonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 215, -1, -1));
        jPanel1.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 320, 300));

        jTabbedPane1.addTab("Crear", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setText("ID a consultar (*)");

        buscarRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarReadActionPerformed(evt);
            }
        });
        buscarRead.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarReadKeyTyped(evt);
            }
        });

        busRead.setText("Buscar");
        busRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busReadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(buscarRead, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(busRead)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarRead, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busRead))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 59, -1, -1));

        cedula.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cedula.setForeground(new java.awt.Color(0, 0, 0));
        cedula.setText("Id");
        jPanel2.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 165, -1, -1));

        celular.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        celular.setForeground(new java.awt.Color(0, 0, 0));
        celular.setText("Nombre");
        jPanel2.add(celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 227, -1, -1));

        idRead.setEnabled(false);
        jPanel2.add(idRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 185, 256, -1));

        nomRead.setEnabled(false);
        nomRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomReadActionPerformed(evt);
            }
        });
        jPanel2.add(nomRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 247, 256, -1));

        titulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        titulo.setText("Consultar LI ");
        jPanel2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, 32));
        jPanel2.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 320, 300));

        jTabbedPane1.addTab("Leer", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cedula1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cedula1.setForeground(new java.awt.Color(0, 0, 0));
        cedula1.setText("Id");
        jPanel3.add(cedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 165, -1, -1));

        celular1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        celular1.setForeground(new java.awt.Color(0, 0, 0));
        celular1.setText("Nombre");
        jPanel3.add(celular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 215, -1, -1));

        idUpdate.setEnabled(false);
        jPanel3.add(idUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 185, 256, -1));
        jPanel3.add(nomUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 241, 256, -1));

        titulo1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        titulo1.setText("Actualizar LI ");
        jPanel3.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 25, -1, 32));

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel13.setText("ID a actualizar (*)");

        buscarUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUpdateActionPerformed(evt);
            }
        });
        buscarUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarUpdateKeyTyped(evt);
            }
        });

        busUpdate.setText("Buscar");
        busUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel13))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buscarUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(busUpdate)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 75, -1, -1));

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        jPanel3.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 271, -1, -1));
        jPanel3.add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 320, 300));

        jTabbedPane1.addTab("Actualizar", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cedula2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cedula2.setForeground(new java.awt.Color(0, 0, 0));
        cedula2.setText("Id");
        jPanel4.add(cedula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 172, -1, -1));

        celular2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        celular2.setForeground(new java.awt.Color(0, 0, 0));
        celular2.setText("Nombre");
        jPanel4.add(celular2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 228, -1, -1));

        idDelete.setEnabled(false);
        jPanel4.add(idDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 192, 256, -1));

        nomDelete.setEnabled(false);
        jPanel4.add(nomDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 248, 256, -1));

        titulo2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        titulo2.setText("Eliminar LI ");
        jPanel4.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, -1, 32));

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel17.setText("ID a eliminar (*)");

        buscarDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDeleteActionPerformed(evt);
            }
        });
        buscarDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarDeleteKeyTyped(evt);
            }
        });

        busDelete.setText("Buscar");
        busDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel17))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buscarDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(busDelete)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 74, -1, -1));

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel4.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 278, -1, -1));
        jPanel4.add(fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 320, 300));

        jTabbedPane1.addTab("Eliminar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomCrearActionPerformed

    private void jBotonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonCrearActionPerformed
        if (!(idCrear.getText().equals("") || nomCrear.getText().equals(""))) {
            LineaInvestigacion a = new LineaInvestigacion(nomCrear.getText(), Long.parseLong(idCrear.getText()));
            if (control.crearInformacion(a)) {
                
                JOptionPane.showMessageDialog(this, "INFORMACIÓN GUARDADA", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                this.idCrear.setText("" + control.generarId());
            } else {
                JOptionPane.showMessageDialog(this, "INFORMACIÓN ERRÓNEA", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "INFORMACIÓN ERRÓNEA", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBotonCrearActionPerformed

    private void buscarReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarReadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarReadActionPerformed

    private void busReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busReadActionPerformed
        LineaInvestigacion lineaRead;
        if (!(this.buscarRead.getText().equals(""))) {
            
            if (!(control.readInformacion(Long.parseLong(buscarRead.getText())) == null)) {
                
                lineaRead = (LineaInvestigacion) control.readInformacion(Long.parseLong(buscarRead.getText()));
                
                this.idRead.setText("" + lineaRead.getId());
                this.nomRead.setText("" + lineaRead.getNombreInv());
                
                JOptionPane.showMessageDialog(this, "DATOS ENCONTRADOS ", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                
            }//verificar que el valor sea diferente de nulo
            else {
                JOptionPane.showMessageDialog(this, "ID NO ENCONTRADA ", "ERROR", JOptionPane.ERROR_MESSAGE);
                this.idRead.setText("");
                this.nomRead.setText("");
                
            }//cedula no  encontrada

        } else {
            JOptionPane.showMessageDialog(this, "ID MAL DIGITADA", "ERROR", JOptionPane.ERROR_MESSAGE);
            this.idRead.setText("");
            this.nomRead.setText("");
            
        }
    }//GEN-LAST:event_busReadActionPerformed

    private void buscarUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarUpdateActionPerformed

    private void busUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busUpdateActionPerformed
        LineaInvestigacion lI = new LineaInvestigacion();
        
        if (!buscarUpdate.getText().equals("")) {
            lI = (LineaInvestigacion) control.readInformacion(Long.parseLong(buscarUpdate.getText()));
            if (lI != null) {
                JOptionPane.showMessageDialog(this, "ENCONTRADO", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                idUpdate.setText("" + lI.getId());
                nomUpdate.setText("" + lI.getNombreInv());
            } else {
                JOptionPane.showMessageDialog(this, "NO HAY REGISTROS", "ERROR", JOptionPane.ERROR_MESSAGE);
                idUpdate.setText("");
                nomUpdate.setText("");
                buscarUpdate.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "INGRESE UNA ID", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_busUpdateActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        if (!idUpdate.getText().equals("")) {
            if (control.updateInformacion(new LineaInvestigacion(nomUpdate.getText(), Long.parseLong(idUpdate.getText())))) {
                JOptionPane.showMessageDialog(this, "INFORMACIÓN ACTUALIZADA", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                JOptionPane.showMessageDialog(this, "NO SE PUDO ACTUALIZAR", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            idUpdate.setText("");
            nomUpdate.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "INFORMACIÓN VACÍA", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void buscarDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarDeleteActionPerformed

    private void busDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busDeleteActionPerformed
        LineaInvestigacion lineaDelete;
        if (!(this.buscarDelete.getText().equals(""))) {
            
            if (!(control.readInformacion(Long.parseLong(buscarDelete.getText())) == null)) {
                
                lineaDelete = (LineaInvestigacion) control.readInformacion(Long.parseLong(buscarDelete.getText()));
                
                this.idDelete.setText("" + lineaDelete.getId());
                this.nomDelete.setText("" + lineaDelete.getNombreInv());
                
                JOptionPane.showMessageDialog(this, "DATOS ENCONTRADOS ", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                
            }//verificar que el valor sea diferente de nulo
            else {
                JOptionPane.showMessageDialog(this, "ID NO ENCONTRADA ", "ERROR", JOptionPane.ERROR_MESSAGE);
                this.idDelete.setText("");
                this.nomDelete.setText("");
                
            }//cedula no  encontrada

        } else {
            JOptionPane.showMessageDialog(this, "ID MAL DIGITADA", "ERROR", JOptionPane.ERROR_MESSAGE);
            this.idDelete.setText("");
            this.nomDelete.setText("");
            
        }
    }//GEN-LAST:event_busDeleteActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        if (!idDelete.getText().equals("")) {
            int a = JOptionPane.showConfirmDialog(this, "¿QUIERES ELIMINAR EL REGISTRO?", "VENTANA CONFIRMACIÓN", JOptionPane.YES_NO_OPTION);
            if (a == 0) {
                if (control.deleteInformacion(Long.parseLong(idDelete.getText()))) {
                    JOptionPane.showMessageDialog(this, "INFORMACIÓN BORRADA", "INFORMACIÓN", JOptionPane.WARNING_MESSAGE);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "NO SE ELIMINO", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                idDelete.setText("");
                nomDelete.setText("");
                
            } else {
                idDelete.setText("");
            }
            nomDelete.setText("");
            
        } else {
            JOptionPane.showMessageDialog(this, "INFORMACIÓN VACÍA", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void nomReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomReadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomReadActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        V_Menu menu = new V_Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void idCrearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idCrearKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_idCrearKeyTyped

    private void buscarReadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarReadKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_buscarReadKeyTyped

    private void buscarUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarUpdateKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_buscarUpdateKeyTyped

    private void buscarDeleteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarDeleteKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_buscarDeleteKeyTyped

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        this.idCrear.setText("" + control.generarId());
        
         //FONDOS
        //instancio la imagen que esta guardada en el Packages
        Image fondoProfe = new ImageIcon(getClass().getResource("/imagenes/linea1.jpg")).getImage();

        //le asigno un tamaño de la imagen 
        Image FondoProfe = fondoProfe.getScaledInstance(this.fondo1.getWidth(), this.fondo1.getHeight(), Image.SCALE_SMOOTH);//le asigno  los valores realaes de el  boton

        ImageIcon icono = new ImageIcon(FondoProfe);

        //asigno la imagen al  boton
        this.fondo1.setIcon(icono);
        this.fondo2.setIcon(icono);
        this.fondo3.setIcon(icono);
        this.fondo4.setIcon(icono);
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void idCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_LineaInvestigacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_LineaInvestigacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_LineaInvestigacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_LineaInvestigacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_LineaInvestigacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton busDelete;
    private javax.swing.JButton busRead;
    private javax.swing.JButton busUpdate;
    private javax.swing.JFormattedTextField buscarDelete;
    private javax.swing.JFormattedTextField buscarRead;
    private javax.swing.JFormattedTextField buscarUpdate;
    private javax.swing.JLabel cedula;
    private javax.swing.JLabel cedula1;
    private javax.swing.JLabel cedula2;
    private javax.swing.JLabel celular;
    private javax.swing.JLabel celular1;
    private javax.swing.JLabel celular2;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JLabel fondo4;
    private javax.swing.JFormattedTextField idCrear;
    private javax.swing.JTextField idDelete;
    private javax.swing.JTextField idRead;
    private javax.swing.JTextField idUpdate;
    private javax.swing.JButton jBotonCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JFormattedTextField nomCrear;
    private javax.swing.JTextField nomDelete;
    private javax.swing.JTextField nomRead;
    private javax.swing.JTextField nomUpdate;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
