/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorPersona;
import java.awt.Image;
import java.time.LocalDate;
import java.time.Month;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Profesor;

/**
 *
 * @author mario
 */
public class V_Profesor extends javax.swing.JFrame {

    ControladorPersona control = new ControladorPersona();

    /**
     * Creates new form V_Profesor
     */
    public V_Profesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Opciones = new javax.swing.JTabbedPane();
        create = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        añoCreate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cedCreate = new javax.swing.JTextField();
        emailCreate = new javax.swing.JTextField();
        apelliCreate = new javax.swing.JTextField();
        nomCreate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        diaCreate = new javax.swing.JTextField();
        mesCreate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();
        read = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        añoRead = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cedRead = new javax.swing.JTextField();
        emailRead = new javax.swing.JTextField();
        apelliRead = new javax.swing.JTextField();
        nomRead = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        diaRead = new javax.swing.JTextField();
        mesRead = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        busCedRead = new javax.swing.JTextField();
        buscarRead = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        apellidosText = new javax.swing.JLabel();
        añoUpdate = new javax.swing.JTextField();
        fechaText = new javax.swing.JLabel();
        cedUpdate = new javax.swing.JTextField();
        emailUpdate = new javax.swing.JTextField();
        apelliUpdate = new javax.swing.JTextField();
        nomUpdate = new javax.swing.JTextField();
        emailText = new javax.swing.JLabel();
        nombreText = new javax.swing.JLabel();
        cedulaText = new javax.swing.JLabel();
        diaUpdate = new javax.swing.JTextField();
        mesUpdate = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        busCedUpdate = new javax.swing.JTextField();
        buscarUpdate = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        actualizar = new javax.swing.JButton();
        fondo3 = new javax.swing.JLabel();
        Delete = new javax.swing.JPanel();
        apellidosText1 = new javax.swing.JLabel();
        añoDelete = new javax.swing.JTextField();
        fechaText1 = new javax.swing.JLabel();
        cedDelete = new javax.swing.JTextField();
        emailDelete = new javax.swing.JTextField();
        apelliDelete = new javax.swing.JTextField();
        nomDelete = new javax.swing.JTextField();
        emailText1 = new javax.swing.JLabel();
        nombreText1 = new javax.swing.JLabel();
        cedulaText1 = new javax.swing.JLabel();
        diaDelete = new javax.swing.JTextField();
        mesDelete = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        busCedDelete = new javax.swing.JTextField();
        buscarDelete = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        borrar = new javax.swing.JButton();
        fondo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRUD profesor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Opciones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                OpcionesFocusGained(evt);
            }
        });

        create.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Apellidos (*)");
        create.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        añoCreate.setBackground(new java.awt.Color(0, 153, 51));
        añoCreate.setForeground(new java.awt.Color(255, 255, 255));
        añoCreate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                añoCreateKeyTyped(evt);
            }
        });
        create.add(añoCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 70, 30));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de Nacimiento (*)");
        create.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        cedCreate.setBackground(new java.awt.Color(0, 153, 51));
        cedCreate.setForeground(new java.awt.Color(255, 255, 255));
        cedCreate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedCreateKeyTyped(evt);
            }
        });
        create.add(cedCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, 30));

        emailCreate.setBackground(new java.awt.Color(0, 153, 51));
        emailCreate.setForeground(new java.awt.Color(255, 255, 255));
        create.add(emailCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 220, 30));

        apelliCreate.setBackground(new java.awt.Color(0, 153, 51));
        apelliCreate.setForeground(new java.awt.Color(255, 255, 255));
        create.add(apelliCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, 30));

        nomCreate.setBackground(new java.awt.Color(0, 153, 51));
        nomCreate.setForeground(new java.awt.Color(255, 255, 255));
        create.add(nomCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, 30));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email (*)");
        create.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre (*)");
        create.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cedula (*)");
        create.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        diaCreate.setBackground(new java.awt.Color(0, 153, 51));
        diaCreate.setForeground(new java.awt.Color(255, 255, 255));
        diaCreate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diaCreateKeyTyped(evt);
            }
        });
        create.add(diaCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 40, 30));

        mesCreate.setBackground(new java.awt.Color(0, 153, 51));
        mesCreate.setForeground(new java.awt.Color(255, 255, 255));
        mesCreate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mesCreateKeyTyped(evt);
            }
        });
        create.add(mesCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 40, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dia");
        create.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mes");
        create.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("año");
        create.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        create.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("CREATE PROFESOR");
        create.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        create.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 540));

        Opciones.addTab("Create", create);

        read.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Apellidos:");
        read.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        añoRead.setEditable(false);
        añoRead.setBackground(new java.awt.Color(0, 153, 51));
        añoRead.setForeground(new java.awt.Color(255, 255, 255));
        read.add(añoRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 70, 30));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha de Nacimiento:");
        read.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        cedRead.setEditable(false);
        cedRead.setBackground(new java.awt.Color(0, 153, 51));
        cedRead.setForeground(new java.awt.Color(255, 255, 255));
        read.add(cedRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, 30));

        emailRead.setEditable(false);
        emailRead.setBackground(new java.awt.Color(0, 153, 51));
        emailRead.setForeground(new java.awt.Color(255, 255, 255));
        read.add(emailRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 220, 30));

        apelliRead.setEditable(false);
        apelliRead.setBackground(new java.awt.Color(0, 153, 51));
        apelliRead.setForeground(new java.awt.Color(255, 255, 255));
        read.add(apelliRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 220, 30));

        nomRead.setEditable(false);
        nomRead.setBackground(new java.awt.Color(0, 153, 51));
        nomRead.setForeground(new java.awt.Color(255, 255, 255));
        read.add(nomRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 220, 30));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email:");
        read.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nombre:");
        read.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cedula:");
        read.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        diaRead.setEditable(false);
        diaRead.setBackground(new java.awt.Color(0, 153, 51));
        diaRead.setForeground(new java.awt.Color(255, 255, 255));
        read.add(diaRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 40, 30));

        mesRead.setEditable(false);
        mesRead.setBackground(new java.awt.Color(0, 153, 51));
        mesRead.setForeground(new java.awt.Color(255, 255, 255));
        read.add(mesRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 40, 30));

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Dia");
        read.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Mes");
        read.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("año");
        read.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));
        read.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 290, -1));

        busCedRead.setBackground(new java.awt.Color(0, 153, 51));
        busCedRead.setForeground(new java.awt.Color(255, 255, 255));
        busCedRead.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                busCedReadKeyTyped(evt);
            }
        });
        read.add(busCedRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, 30));

        buscarRead.setText("Buscar");
        buscarRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarReadActionPerformed(evt);
            }
        });
        read.add(buscarRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("READ PROFESOR");
        read.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Digite una  cedula(*)");
        read.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        read.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 540));

        Opciones.addTab("Read", read);

        update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        apellidosText.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        apellidosText.setForeground(new java.awt.Color(255, 255, 255));
        apellidosText.setText("Apellidos:");
        update.add(apellidosText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        añoUpdate.setBackground(new java.awt.Color(0, 153, 51));
        añoUpdate.setForeground(new java.awt.Color(255, 255, 255));
        añoUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                añoUpdateKeyTyped(evt);
            }
        });
        update.add(añoUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 70, 30));

        fechaText.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        fechaText.setForeground(new java.awt.Color(255, 255, 255));
        fechaText.setText("Fecha de Nacimiento:");
        update.add(fechaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        cedUpdate.setEditable(false);
        cedUpdate.setBackground(new java.awt.Color(0, 153, 51));
        cedUpdate.setForeground(new java.awt.Color(255, 255, 255));
        update.add(cedUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, 30));

        emailUpdate.setBackground(new java.awt.Color(0, 153, 51));
        emailUpdate.setForeground(new java.awt.Color(255, 255, 255));
        update.add(emailUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 220, 30));

        apelliUpdate.setBackground(new java.awt.Color(0, 153, 51));
        apelliUpdate.setForeground(new java.awt.Color(255, 255, 255));
        update.add(apelliUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 220, 30));

        nomUpdate.setBackground(new java.awt.Color(0, 153, 51));
        nomUpdate.setForeground(new java.awt.Color(255, 255, 255));
        update.add(nomUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 220, 30));

        emailText.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        emailText.setForeground(new java.awt.Color(255, 255, 255));
        emailText.setText("Email:");
        update.add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        nombreText.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        nombreText.setForeground(new java.awt.Color(255, 255, 255));
        nombreText.setText("Nombre:");
        update.add(nombreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        cedulaText.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cedulaText.setForeground(new java.awt.Color(255, 255, 255));
        cedulaText.setText("Cedula:");
        update.add(cedulaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        diaUpdate.setBackground(new java.awt.Color(0, 153, 51));
        diaUpdate.setForeground(new java.awt.Color(255, 255, 255));
        diaUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diaUpdateKeyTyped(evt);
            }
        });
        update.add(diaUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 40, 30));

        mesUpdate.setBackground(new java.awt.Color(0, 153, 51));
        mesUpdate.setForeground(new java.awt.Color(255, 255, 255));
        mesUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mesUpdateKeyTyped(evt);
            }
        });
        update.add(mesUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 40, 30));

        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Dia");
        update.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Mes");
        update.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel26.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("año");
        update.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));
        update.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 290, -1));

        busCedUpdate.setBackground(new java.awt.Color(0, 153, 51));
        busCedUpdate.setForeground(new java.awt.Color(255, 255, 255));
        busCedUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                busCedUpdateKeyTyped(evt);
            }
        });
        update.add(busCedUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, 30));

        buscarUpdate.setText("Buscar");
        buscarUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUpdateActionPerformed(evt);
            }
        });
        update.add(buscarUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel27.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("UPDATE  PROFESOR");
        update.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Digite una  cedula(*)");
        update.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        update.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));
        update.add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 540));

        Opciones.addTab("Update", update);

        Delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        apellidosText1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        apellidosText1.setForeground(new java.awt.Color(255, 255, 255));
        apellidosText1.setText("Apellidos:");
        Delete.add(apellidosText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        añoDelete.setEditable(false);
        añoDelete.setBackground(new java.awt.Color(0, 153, 51));
        añoDelete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.add(añoDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 70, 30));

        fechaText1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        fechaText1.setForeground(new java.awt.Color(255, 255, 255));
        fechaText1.setText("Fecha de Nacimiento:");
        Delete.add(fechaText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        cedDelete.setEditable(false);
        cedDelete.setBackground(new java.awt.Color(0, 153, 51));
        cedDelete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.add(cedDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, 30));

        emailDelete.setEditable(false);
        emailDelete.setBackground(new java.awt.Color(0, 153, 51));
        emailDelete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.add(emailDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 220, 30));

        apelliDelete.setEditable(false);
        apelliDelete.setBackground(new java.awt.Color(0, 153, 51));
        apelliDelete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.add(apelliDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 220, 30));

        nomDelete.setEditable(false);
        nomDelete.setBackground(new java.awt.Color(0, 153, 51));
        nomDelete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.add(nomDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 220, 30));

        emailText1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        emailText1.setForeground(new java.awt.Color(255, 255, 255));
        emailText1.setText("Email:");
        Delete.add(emailText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        nombreText1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        nombreText1.setForeground(new java.awt.Color(255, 255, 255));
        nombreText1.setText("Nombre:");
        Delete.add(nombreText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        cedulaText1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cedulaText1.setForeground(new java.awt.Color(255, 255, 255));
        cedulaText1.setText("Cedula:");
        Delete.add(cedulaText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        diaDelete.setEditable(false);
        diaDelete.setBackground(new java.awt.Color(0, 153, 51));
        diaDelete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.add(diaDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 40, 30));

        mesDelete.setEditable(false);
        mesDelete.setBackground(new java.awt.Color(0, 153, 51));
        mesDelete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.add(mesDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 40, 30));

        jLabel29.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Dia");
        Delete.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel30.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Mes");
        Delete.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel31.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("año");
        Delete.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));
        Delete.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 290, -1));

        busCedDelete.setBackground(new java.awt.Color(0, 153, 51));
        busCedDelete.setForeground(new java.awt.Color(255, 255, 255));
        busCedDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                busCedDeleteKeyTyped(evt);
            }
        });
        Delete.add(busCedDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, 30));

        buscarDelete.setText("Buscar");
        buscarDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDeleteActionPerformed(evt);
            }
        });
        Delete.add(buscarDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel32.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("DELETE PROFESOR");
        Delete.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel33.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Digite una  cedula(*)");
        Delete.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        borrar.setText("Borrar ");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        Delete.add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));
        Delete.add(fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 540));

        Opciones.addTab("Delete", Delete);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 306, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Opciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 563, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
       
        Profesor nuevo=new Profesor();
       try {
            if (!(this.cedCreate.getText().equals("") || this.nomCreate.getText().equals("")
                    || this.apelliCreate.getText().equals("")
                    || this.emailCreate.getText().equals("")
                    || this.diaCreate.getText().equals("")
                    || this.mesCreate.getText().equals("")
                    || this.añoCreate.getText().equals(""))) {

             
                
                nuevo.setCedula(Long.parseLong(this.cedCreate.getText())); //le da una cedula al  objeto

                nuevo.setNombre(this.nomCreate.getText()); //le da un nombre al  objeto 

                nuevo.setApellidos(this.apelliCreate.getText()); //le da los apellidos al  objeto

                nuevo.setEmail(this.emailCreate.getText()); //le da un email  al objeto 

                nuevo.setFechaNacimiento(LocalDate.of(Integer.parseInt(this.añoCreate.getText()), Integer.parseInt(this.mesCreate.getText()), Integer.parseInt(this.diaCreate.getText())));

                if (control.createPersona(nuevo)) {
                    JOptionPane.showMessageDialog(this, "DATOS GUARDADOS CORRECTAMENTE", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                    this.cedCreate.setText("");
                    this.nomCreate.setText("");
                    this.apelliCreate.setText("");
                    this.emailCreate.setText("");
                    this.añoCreate.setText("");
                    this.mesCreate.setText("");
                    this.diaCreate.setText("");
                    

                } else {
                    JOptionPane.showMessageDialog(this, "NO SE PUDIERON GUARDAR LOS DATOS", "ERROR", JOptionPane.ERROR_MESSAGE);
                     this.cedCreate.setText("");
                    this.nomCreate.setText("");
                    this.apelliCreate.setText("");
                    this.emailCreate.setText("");
                    this.añoCreate.setText("");
                    this.mesCreate.setText("");
                    this.diaCreate.setText("");
                }

            } else {
                JOptionPane.showMessageDialog(this, "PORFAVOR DIGITE TODOS LOS CAMPOS ", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
       } catch (Exception e) {
           // JOptionPane.showMessageDialog(this, "ERROR FECHA MAL  DIGITADA \n" + e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void buscarReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarReadActionPerformed
        Profesor profeRead;
        if (!(this.busCedRead.getText().equals(""))) {

            if (!(control.readPersona(Long.parseLong(busCedRead.getText())) == null)) {

                profeRead = (Profesor) control.readPersona(Long.parseLong(busCedRead.getText()));

                this.cedRead.setText("" + profeRead.getCedula());
                this.nomRead.setText("" + profeRead.getNombre());
                this.apelliRead.setText("" + profeRead.getApellidos());
                this.emailRead.setText("" + profeRead.getEmail());
                this.añoRead.setText("" + profeRead.getFechaNacimiento().getYear());
                this.mesRead.setText("" + profeRead.getFechaNacimiento().getMonthValue());
                this.diaRead.setText("" + profeRead.getFechaNacimiento().getDayOfMonth());

                JOptionPane.showMessageDialog(this, "DATOS ENCONTRADOS ", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

            }//verificar que el valor sea diferente de nulo
            else {
                JOptionPane.showMessageDialog(this, "CEDULA NO ENCONTRADA ", "ERROR", JOptionPane.ERROR_MESSAGE);
                this.cedRead.setText("");
                this.nomRead.setText("");
                this.apelliRead.setText("");
                this.emailRead.setText("");
                this.añoRead.setText("");
                this.mesRead.setText("");
                this.diaRead.setText("");

            }//cedula no  encontrada

        } else {
            JOptionPane.showMessageDialog(this, "CEDULA MAL DIGITADA", "ERROR", JOptionPane.ERROR_MESSAGE);
            this.cedRead.setText("");
            this.nomRead.setText("");
            this.apelliRead.setText("");
            this.emailRead.setText("");
            this.añoRead.setText("");
            this.mesRead.setText("");
            this.diaRead.setText("");

        }
    }//GEN-LAST:event_buscarReadActionPerformed

    private void buscarUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUpdateActionPerformed
        Profesor profeUpdate;
        if (!(this.busCedUpdate.getText().equals(""))) {

            if (!(control.readPersona(Long.parseLong(busCedUpdate.getText())) == null)) {

                profeUpdate = (Profesor) control.readPersona(Long.parseLong(busCedUpdate.getText()));

                this.cedUpdate.setText("" + profeUpdate.getCedula());
                this.nomUpdate.setText("" + profeUpdate.getNombre());
                this.apelliUpdate.setText("" + profeUpdate.getApellidos());
                this.emailUpdate.setText("" + profeUpdate.getEmail());
                this.añoUpdate.setText("" + profeUpdate.getFechaNacimiento().getYear());
                this.mesUpdate.setText("" + profeUpdate.getFechaNacimiento().getMonthValue());
                this.diaUpdate.setText("" + profeUpdate.getFechaNacimiento().getDayOfMonth());

                JOptionPane.showMessageDialog(this, "DATOS ENCONTRADOS ", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

                this.nombreText.setText("Digite el  nuevo nombre (*)");
                this.apellidosText.setText("Digite el  nuevo apellido (*)");
                this.emailText.setText("Digite el  nuevo  email (*)");
                this.fechaText.setText("Digite la nueva fecha de nacimiento (*)");

                this.nomUpdate.setText("");
                this.apelliUpdate.setText("");
                this.emailUpdate.setText("");
                this.añoUpdate.setText("");
                this.mesUpdate.setText("");
                this.diaUpdate.setText("");

            }//verificar que el valor sea diferente de nulo
            else {
                JOptionPane.showMessageDialog(this, "CEDULA NO ENCONTRADA ", "ERROR", JOptionPane.ERROR_MESSAGE);
                this.cedUpdate.setText("");
                this.nomUpdate.setText("");
                this.apelliUpdate.setText("");
                this.emailUpdate.setText("");
                this.añoUpdate.setText("");
                this.mesUpdate.setText("");
                this.diaUpdate.setText("");

            }//cedula no  encontrada

        } else {
            JOptionPane.showMessageDialog(this, "CEDULA MAL DIGITADA", "ERROR", JOptionPane.ERROR_MESSAGE);
            this.cedUpdate.setText("");
            this.nomUpdate.setText("");
            this.apelliUpdate.setText("");
            this.emailUpdate.setText("");
            this.añoUpdate.setText("");
            this.mesUpdate.setText("");
            this.diaUpdate.setText("");

        }
    }//GEN-LAST:event_buscarUpdateActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        Profesor actualizacion = new Profesor();
        actualizacion.setCedula(Long.parseLong(this.cedUpdate.getText()));
        actualizacion.setNombre(this.nomUpdate.getText());
        actualizacion.setApellidos(this.apelliUpdate.getText());
        actualizacion.setEmail(this.emailUpdate.getText());
        actualizacion.setFechaNacimiento(LocalDate.of(Integer.parseInt(this.añoUpdate.getText()), Integer.parseInt(this.mesUpdate.getText()), Integer.parseInt(this.diaUpdate.getText())));

        if (control.updatePersona(actualizacion)) {
            JOptionPane.showMessageDialog(this, "DATOS ACTUALIZADOS", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

            this.cedUpdate.setText("");
            this.nomUpdate.setText("");
            this.apelliUpdate.setText("");
            this.emailUpdate.setText("");
            this.añoUpdate.setText("");
            this.mesUpdate.setText("");
            this.diaUpdate.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "DATOS NO ACTUALIZADOS", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void buscarDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDeleteActionPerformed
        Profesor profeDelete;
        if (!(this.busCedDelete.getText().equals(""))) {

            if (!(control.readPersona(Long.parseLong(busCedDelete.getText())) == null)) {

                profeDelete = (Profesor) control.readPersona(Long.parseLong(busCedDelete.getText()));

                this.cedDelete.setText("" + profeDelete.getCedula());
                this.nomDelete.setText("" + profeDelete.getNombre());
                this.apelliDelete.setText("" + profeDelete.getApellidos());
                this.emailDelete.setText("" + profeDelete.getEmail());
                this.añoDelete.setText("" + profeDelete.getFechaNacimiento().getYear());
                this.mesDelete.setText("" + profeDelete.getFechaNacimiento().getMonthValue());
                this.diaDelete.setText("" + profeDelete.getFechaNacimiento().getDayOfMonth());

                JOptionPane.showMessageDialog(this, "DATOS ENCONTRADOS ", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

            }//verificar que el valor sea diferente de nulo
            else {
                JOptionPane.showMessageDialog(this, "CEDULA NO ENCONTRADA ", "ERROR", JOptionPane.ERROR_MESSAGE);
                this.cedDelete.setText("");
                this.nomDelete.setText("");
                this.apelliDelete.setText("");
                this.emailDelete.setText("");
                this.añoDelete.setText("");
                this.mesDelete.setText("");
                this.diaDelete.setText("");

            }//cedula no  encontrada

        } else {
            JOptionPane.showMessageDialog(this, "CEDULA MAL DIGITADA", "ERROR", JOptionPane.ERROR_MESSAGE);
            this.cedDelete.setText("");
            this.nomDelete.setText("");
            this.apelliDelete.setText("");
            this.emailDelete.setText("");
            this.añoDelete.setText("");
            this.mesDelete.setText("");
            this.diaDelete.setText("");

        }
    }//GEN-LAST:event_buscarDeleteActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        if (control.deletePersona(Long.parseLong(this.cedDelete.getText()))) {
            JOptionPane.showMessageDialog(this, "DATOS ELIMINADOS CORRECTAMENTE", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
            this.cedDelete.setText("");
            this.nomDelete.setText("");
            this.apelliDelete.setText("");
            this.emailDelete.setText("");
            this.añoDelete.setText("");
            this.mesDelete.setText("");
            this.diaDelete.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "NO FUE POSIBLE ELIMINAR LOS DATOS", "INFORMACION", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_borrarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      V_Menu menu=new V_Menu();
      menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void cedCreateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedCreateKeyTyped
      char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_cedCreateKeyTyped

    private void diaCreateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diaCreateKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_diaCreateKeyTyped

    private void mesCreateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesCreateKeyTyped
     char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_mesCreateKeyTyped

    private void añoCreateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_añoCreateKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_añoCreateKeyTyped

    private void busCedReadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busCedReadKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_busCedReadKeyTyped

    private void diaUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diaUpdateKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_diaUpdateKeyTyped

    private void mesUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesUpdateKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_mesUpdateKeyTyped

    private void añoUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_añoUpdateKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_añoUpdateKeyTyped

    private void busCedDeleteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busCedDeleteKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_busCedDeleteKeyTyped

    private void busCedUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busCedUpdateKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_busCedUpdateKeyTyped

    private void OpcionesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OpcionesFocusGained
        //FONDOS
        //instancio la imagen que esta guardada en el Packages
        Image fondoProfe = new ImageIcon(getClass().getResource("/imagenes/fondoprofesor.jpg")).getImage();

        //le asigno un tamaño de la imagen 
        Image FondoProfe = fondoProfe.getScaledInstance(this.fondo1.getWidth(), this.fondo1.getHeight(), Image.SCALE_SMOOTH);//le asigno  los valores realaes de el  boton

        ImageIcon icono = new ImageIcon(FondoProfe);

        //asigno la imagen al  boton
        this.fondo1.setIcon(icono);
        this.fondo2.setIcon(icono);
        this.fondo3.setIcon(icono);
        this.fondo4.setIcon(icono);
    }//GEN-LAST:event_OpcionesFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Profesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Delete;
    private javax.swing.JButton Guardar;
    private javax.swing.JTabbedPane Opciones;
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField apelliCreate;
    private javax.swing.JTextField apelliDelete;
    private javax.swing.JTextField apelliRead;
    private javax.swing.JTextField apelliUpdate;
    private javax.swing.JLabel apellidosText;
    private javax.swing.JLabel apellidosText1;
    private javax.swing.JTextField añoCreate;
    private javax.swing.JTextField añoDelete;
    private javax.swing.JTextField añoRead;
    private javax.swing.JTextField añoUpdate;
    private javax.swing.JButton borrar;
    private javax.swing.JTextField busCedDelete;
    private javax.swing.JTextField busCedRead;
    private javax.swing.JTextField busCedUpdate;
    private javax.swing.JButton buscarDelete;
    private javax.swing.JButton buscarRead;
    private javax.swing.JButton buscarUpdate;
    private javax.swing.JTextField cedCreate;
    private javax.swing.JTextField cedDelete;
    private javax.swing.JTextField cedRead;
    private javax.swing.JTextField cedUpdate;
    private javax.swing.JLabel cedulaText;
    private javax.swing.JLabel cedulaText1;
    private javax.swing.JPanel create;
    private javax.swing.JTextField diaCreate;
    private javax.swing.JTextField diaDelete;
    private javax.swing.JTextField diaRead;
    private javax.swing.JTextField diaUpdate;
    private javax.swing.JTextField emailCreate;
    private javax.swing.JTextField emailDelete;
    private javax.swing.JTextField emailRead;
    private javax.swing.JLabel emailText;
    private javax.swing.JLabel emailText1;
    private javax.swing.JTextField emailUpdate;
    private javax.swing.JLabel fechaText;
    private javax.swing.JLabel fechaText1;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JLabel fondo4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField mesCreate;
    private javax.swing.JTextField mesDelete;
    private javax.swing.JTextField mesRead;
    private javax.swing.JTextField mesUpdate;
    private javax.swing.JTextField nomCreate;
    private javax.swing.JTextField nomDelete;
    private javax.swing.JTextField nomRead;
    private javax.swing.JTextField nomUpdate;
    private javax.swing.JLabel nombreText;
    private javax.swing.JLabel nombreText1;
    private javax.swing.JPanel read;
    private javax.swing.JPanel update;
    // End of variables declaration//GEN-END:variables
}
