/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorInformacion;
import controlador.ControladorPersona;
import controlador.ControladorProyecto;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Estudiante;
import modelo.LineaInvestigacion;
import modelo.Modalidad;
import modelo.Profesor;
import modelo.Proyecto;

/**
 *
 * @author mario
 */
public class V_Proyecto extends javax.swing.JFrame {

    Modalidad modalidad = null;
    LineaInvestigacion linea = null;
    ArrayList<Profesor> ArrayProfe = new ArrayList<>();
    ArrayList<Estudiante> ArrayEstudiantes = new ArrayList<>();

    ControladorPersona controlPersona = new ControladorPersona();

    ControladorProyecto controlProyecto = new ControladorProyecto();

    ControladorInformacion controlInformacion = new ControladorInformacion();

    /**
     * Creates new form V_Proyecto
     */
    public V_Proyecto() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Create = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        notaCreate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombreCreate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        generalCreate = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        modalidadesCreate = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        lineasInvestigacionCreate = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        especificoCreate = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        idCreate = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        fondo1 = new javax.swing.JLabel();
        Update = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        generalUpdate = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        especificosUpdate = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        actualizar = new javax.swing.JButton();
        botonProfesor = new javax.swing.JButton();
        botonEstudiante = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        busIdUpdate = new javax.swing.JTextField();
        nombreUpdate = new javax.swing.JTextField();
        idUpdate = new javax.swing.JTextField();
        comboLineas = new javax.swing.JComboBox<>();
        comboModalidades = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        notaUpdate = new javax.swing.JTextField();
        fondo2 = new javax.swing.JLabel();
        Read = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        busIdRead = new javax.swing.JTextField();
        buscarRead = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        nombreRead = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        profesRead = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        estudiantesRead = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        modRead = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        lineaRead = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        generalRead = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        especificosRead = new javax.swing.JTextArea();
        fondo3 = new javax.swing.JLabel();
        Delete = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        especificosDelete = new javax.swing.JTextArea();
        busIdDelete = new javax.swing.JTextField();
        buscarDelete = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        modDelete = new javax.swing.JTextField();
        idDelete = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lineaDelete = new javax.swing.JTextField();
        nombreDelete = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        generalDelete = new javax.swing.JTextArea();
        jLabel40 = new javax.swing.JLabel();
        vDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        profesoresDelete = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        estudiantesDelete = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        notaDelete = new javax.swing.JTextField();
        fondo4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel5.setText("jLabel5");

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRUD proyecto");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        Create.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setText("CREAR PROYECTO");
        Create.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setText("Objetivos especificos del proyecto (*)");
        Create.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        notaCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaCreateActionPerformed(evt);
            }
        });
        Create.add(notaCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 240, 30));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("Id(*)");
        Create.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        Create.add(nombreCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 240, 30));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("nombre del proyecto(*)");
        Create.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        generalCreate.setColumns(20);
        generalCreate.setRows(5);
        jScrollPane1.setViewportView(generalCreate);

        Create.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 240, 80));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setText("Objetivo general del proyecto (*)");
        Create.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setText("Modalidad(*)");
        Create.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        modalidadesCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modalidadesCreateActionPerformed(evt);
            }
        });
        Create.add(modalidadesCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 180, 30));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setText("Linea de investigacion(*)");
        Create.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        lineasInvestigacionCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineasInvestigacionCreateActionPerformed(evt);
            }
        });
        Create.add(lineasInvestigacionCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 180, 30));

        especificoCreate.setColumns(20);
        especificoCreate.setRows(5);
        jScrollPane3.setViewportView(especificoCreate);

        Create.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 240, 80));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setText("Nota(*)");
        Create.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        idCreate.setEditable(false);
        idCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCreateActionPerformed(evt);
            }
        });
        idCreate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idCreateKeyTyped(evt);
            }
        });
        Create.add(idCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 240, 30));

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        Create.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));
        Create.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 560));

        jTabbedPane1.addTab("Create", Create);

        Update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel23.setText("Leer Proyecto");
        Update.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 20, -1, -1));

        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel24.setText("Id");
        Update.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 63, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel25.setText("nombre del proyecto");
        Update.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 163, -1, -1));

        jLabel26.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel26.setText("Objetivo general del proyecto ");
        Update.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 246, -1, -1));

        generalUpdate.setColumns(20);
        generalUpdate.setRows(5);
        jScrollPane7.setViewportView(generalUpdate);

        Update.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 282, 240, 80));

        jLabel27.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel27.setText("Objetivos especificos del proyecto");
        Update.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 393, -1, -1));

        especificosUpdate.setColumns(20);
        especificosUpdate.setRows(5);
        jScrollPane8.setViewportView(especificosUpdate);

        Update.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 463, 240, 80));

        jLabel28.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel28.setText("Modalidad");
        Update.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 163, -1, -1));

        jLabel29.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel29.setText("Linea de investigacion");
        Update.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 79, -1, -1));

        jLabel30.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel30.setText("profesor(es)");
        Update.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 249, -1, -1));

        jLabel31.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel31.setText("Estudiante(es)");
        Update.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 342, -1, -1));

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        Update.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 522, -1, -1));

        botonProfesor.setText("Profesor");
        Update.add(botonProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 273, 240, -1));

        botonEstudiante.setText("Estudiante");
        Update.add(botonEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 366, 240, -1));

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        Update.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 13, -1, -1));

        busIdUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                busIdUpdateKeyTyped(evt);
            }
        });
        Update.add(busIdUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 13, 233, 32));

        nombreUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUpdateActionPerformed(evt);
            }
        });
        Update.add(nombreUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 187, 233, 32));

        idUpdate.setEditable(false);
        idUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idUpdateKeyTyped(evt);
            }
        });
        Update.add(idUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 87, 233, 32));

        Update.add(comboLineas, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 115, 240, -1));

        Update.add(comboModalidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 199, 240, -1));

        jLabel9.setText("Nota:");
        Update.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 429, -1, -1));
        Update.add(notaUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 452, 240, 36));
        Update.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 560));

        jTabbedPane1.addTab("Update", Update);

        Read.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel14.setText("Leer Proyecto");
        Read.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        busIdRead.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                busIdReadKeyTyped(evt);
            }
        });
        Read.add(busIdRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 220, 40));

        buscarRead.setText("Buscar");
        buscarRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarReadActionPerformed(evt);
            }
        });
        Read.add(buscarRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, 40));

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel16.setText("nombre del proyecto");
        Read.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        nombreRead.setEditable(false);
        nombreRead.setEnabled(false);
        Read.add(nombreRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 240, 30));

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel17.setText("Objetivo general del proyecto ");
        Read.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        profesRead.setEditable(false);
        profesRead.setColumns(20);
        profesRead.setRows(5);
        profesRead.setEnabled(false);
        jScrollPane5.setViewportView(profesRead);

        Read.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 240, 80));

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel18.setText("Objetivos especificos del proyecto");
        Read.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        estudiantesRead.setEditable(false);
        estudiantesRead.setColumns(20);
        estudiantesRead.setRows(5);
        estudiantesRead.setEnabled(false);
        jScrollPane6.setViewportView(estudiantesRead);

        Read.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 240, 80));

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel19.setText("Modalidad");
        Read.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        modRead.setEditable(false);
        modRead.setEnabled(false);
        Read.add(modRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 240, 30));

        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel20.setText("Linea de investigacion");
        Read.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        lineaRead.setEditable(false);
        lineaRead.setEnabled(false);
        Read.add(lineaRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 240, 30));

        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel21.setText("profesor(es)");
        Read.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel22.setText("Estudiante(es)");
        Read.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        generalRead.setEditable(false);
        generalRead.setColumns(20);
        generalRead.setRows(5);
        generalRead.setEnabled(false);
        jScrollPane11.setViewportView(generalRead);

        Read.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 240, 80));

        especificosRead.setEditable(false);
        especificosRead.setColumns(20);
        especificosRead.setRows(5);
        especificosRead.setEnabled(false);
        jScrollPane12.setViewportView(especificosRead);

        Read.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 240, 80));
        Read.add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 560));

        jTabbedPane1.addTab("Read", Read);

        Delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel32.setText("Objetivos especificos del proyecto");
        Delete.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 406, -1, -1));

        jLabel33.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel33.setText("Leer Proyecto");
        Delete.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 34, -1, -1));

        especificosDelete.setEditable(false);
        especificosDelete.setColumns(20);
        especificosDelete.setRows(5);
        especificosDelete.setEnabled(false);
        jScrollPane9.setViewportView(especificosDelete);

        Delete.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 446, 240, 80));

        busIdDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                busIdDeleteKeyTyped(evt);
            }
        });
        Delete.add(busIdDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 34, 220, 30));

        buscarDelete.setText("Buscar");
        buscarDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDeleteActionPerformed(evt);
            }
        });
        Delete.add(buscarDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 34, -1, -1));

        jLabel34.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel34.setText("Modalidad");
        Delete.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 378, -1, -1));

        jLabel35.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel35.setText("Id");
        Delete.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 86, -1, -1));

        modDelete.setEditable(false);
        modDelete.setEnabled(false);
        Delete.add(modDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 402, 240, 30));

        idDelete.setEditable(false);
        idDelete.setEnabled(false);
        idDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDeleteActionPerformed(evt);
            }
        });
        Delete.add(idDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 116, 240, 30));

        jLabel36.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel36.setText("Linea de investigacion");
        Delete.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 86, -1, -1));

        jLabel37.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel37.setText("nombre del proyecto");
        Delete.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 166, -1, -1));

        lineaDelete.setEditable(false);
        lineaDelete.setEnabled(false);
        Delete.add(lineaDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 116, 240, 30));

        nombreDelete.setEditable(false);
        nombreDelete.setEnabled(false);
        Delete.add(nombreDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 196, 240, 30));

        jLabel38.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel38.setText("profesor(es)");
        Delete.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 166, -1, -1));

        jLabel39.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel39.setText("Objetivo general del proyecto ");
        Delete.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 246, -1, -1));

        generalDelete.setEditable(false);
        generalDelete.setColumns(20);
        generalDelete.setRows(5);
        generalDelete.setEnabled(false);
        jScrollPane10.setViewportView(generalDelete);

        Delete.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 286, 240, 80));

        jLabel40.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel40.setText("Estudiante(es)");
        Delete.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 267, -1, -1));

        vDelete.setText("Eliminar");
        vDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vDeleteActionPerformed(evt);
            }
        });
        Delete.add(vDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 522, -1, -1));

        profesoresDelete.setEditable(false);
        profesoresDelete.setColumns(20);
        profesoresDelete.setRows(5);
        jScrollPane2.setViewportView(profesoresDelete);

        Delete.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 192, 247, 69));

        estudiantesDelete.setEditable(false);
        estudiantesDelete.setColumns(20);
        estudiantesDelete.setRows(5);
        jScrollPane4.setViewportView(estudiantesDelete);

        Delete.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 291, 247, 69));

        jLabel10.setText("Nota");
        Delete.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 450, -1, -1));

        notaDelete.setEditable(false);
        Delete.add(notaDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 472, 240, 29));
        Delete.add(fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 560));

        jTabbedPane1.addTab("Delete", Delete);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        //FONDOS
        //instancio la imagen que esta guardada en el Packages
        Image fondoProfe = new ImageIcon(getClass().getResource("/imagenes/proyecto.jpg")).getImage();

        //le asigno un tamaño de la imagen 
        Image FondoProfe = fondoProfe.getScaledInstance(this.fondo1.getWidth(), this.fondo1.getHeight(), Image.SCALE_SMOOTH);//le asigno  los valores realaes de el  boton

        ImageIcon icono = new ImageIcon(FondoProfe);

        //asigno la imagen al  boton
        this.fondo1.setIcon(icono);
        this.fondo2.setIcon(icono);
        this.fondo3.setIcon(icono);
        this.fondo4.setIcon(icono);
        
        
        this.idCreate.setText("" + controlProyecto.generarId());
        ArrayList<Modalidad> noms3 = controlInformacion.enviarModalidad();
        ArrayList<LineaInvestigacion> noms4 = controlInformacion.enviarLineaInvestigacion();
        this.modalidadesCreate.removeAllItems();
        this.lineasInvestigacionCreate.removeAllItems();
        this.comboModalidades.removeAllItems();
        this.comboLineas.removeAllItems();
        this.modalidadesCreate.addItem("");
        this.lineasInvestigacionCreate.addItem("");
        this.comboModalidades.addItem("");
        this.comboLineas.addItem("");
        for (int i = 0; i < noms3.size(); i++) {
            this.modalidadesCreate.addItem("" + noms3.get(i).getId());
            this.comboModalidades.addItem("" + noms3.get(i).getId());
        }//estudiantesComboBox

        for (int i = 0; i < noms4.size(); i++) {
            this.lineasInvestigacionCreate.addItem("" + noms4.get(i).getId());
            this.comboLineas.addItem("" + noms4.get(i).getId());
        }//estudiantesComboBox


    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        V_Menu menu = new V_Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void idCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCreateActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        Proyecto nuevo = new Proyecto();

        try {
            if (!(this.idCreate.getText().equals("")
                    || this.nombreCreate.equals("")
                    || this.generalCreate.getText().equals("")
                    || this.especificoCreate.getText().equals("")
                    || this.modalidadesCreate.getSelectedItem().equals("")
                    || this.lineasInvestigacionCreate.getSelectedItem().equals(""))) {

                this.modalidad = (Modalidad) controlInformacion.readInformacion(Long.parseLong((String) modalidadesCreate.getSelectedItem()));
                this.linea = (LineaInvestigacion) controlInformacion.readInformacion(Long.parseLong((String) lineasInvestigacionCreate.getSelectedItem()));
                nuevo.setId(Long.parseLong(this.idCreate.getText()));
                nuevo.setNombreProyecto(this.nombreCreate.getText());
                nuevo.setObjetivoGeneral(this.generalCreate.getText());
                nuevo.setObjetivoEspecifico(this.especificoCreate.getText());
                nuevo.setModalidad(modalidad);
                nuevo.setLinea(linea);
                nuevo.setProfesores(ArrayProfe);
                nuevo.setEstudiantes(ArrayEstudiantes);
                if (!(this.notaCreate.getText().equals(""))) {
                    nuevo.setNota(Double.parseDouble(this.notaCreate.getText()));
                } else {
                    nuevo.setNota(0);
                }
                if (controlProyecto.createProyecto(nuevo)) {

                    JOptionPane.showMessageDialog(this, "DATOS GUARDADOS ", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                    this.idCreate.setText("" + controlProyecto.generarId());
                    this.nombreCreate.setText("");
                    this.generalCreate.setText("");
                    this.especificoCreate.setText("");
                    this.notaCreate.setText("");
                    this.idCreate.setText("");
                    this.modalidadesCreate.setSelectedItem("");
                    this.lineasInvestigacionCreate.setSelectedItem("");

                } else {
                    JOptionPane.showMessageDialog(this, "NO SE PUDIERON GUARDAR LOS DATOS", "ERROR", JOptionPane.ERROR_MESSAGE);
                    this.idCreate.setText("");

                }

            } else {
                JOptionPane.showMessageDialog(this, "PORFAVOR DIGITE TODOS LOS CAMPOS ", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR FECHA MAL  DIGITADA \n" + e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_guardarActionPerformed

    private void lineasInvestigacionCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineasInvestigacionCreateActionPerformed

    }//GEN-LAST:event_lineasInvestigacionCreateActionPerformed

    private void notaCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaCreateActionPerformed

    private void modalidadesCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modalidadesCreateActionPerformed

    }//GEN-LAST:event_modalidadesCreateActionPerformed

    private void buscarReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarReadActionPerformed
        Proyecto proyectoRead;
        if (!(this.busIdRead.equals(""))) {

            if (!(controlProyecto.readProyecto(Long.parseLong(this.busIdRead.getText())) == null)) {

                proyectoRead = controlProyecto.readProyecto(Long.parseLong(busIdRead.getText()));

                this.nombreRead.setText("" + proyectoRead.getNombreProyecto());
                this.generalRead.setText("" + proyectoRead.getObjetivoGeneral());
                this.especificosRead.setText("" + proyectoRead.getObjetivoEspecifico());
                this.modRead.setText("" + proyectoRead.getModalidad().getNombreMod());
                this.lineaRead.setText(proyectoRead.getLinea().getNombreInv());
                this.profesRead.setText(proyectoRead.mostrarProfesores());

                JOptionPane.showMessageDialog(this, "DATOS ENCONTRADOS ", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

            }//verificar que el valor sea diferente de nulo
            else {
                JOptionPane.showMessageDialog(this, "CEDULA NO ENCONTRADA ", "ERROR", JOptionPane.ERROR_MESSAGE);

            }//cedula no  encontrada

        } else {
            JOptionPane.showMessageDialog(this, "CEDULA MAL DIGITADA", "ERROR", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_buscarReadActionPerformed

    private void buscarDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDeleteActionPerformed
        Proyecto proyectoDelete;
        try {

            if (!(this.busIdDelete.equals(""))) {

                if (!(controlProyecto.readProyecto(Long.parseLong(this.busIdDelete.getText())) == null)) {

                    proyectoDelete = controlProyecto.readProyecto(Long.parseLong(busIdDelete.getText()));
                    this.idDelete.setText("" + proyectoDelete.getId());
                    this.nombreDelete.setText("" + proyectoDelete.getNombreProyecto());
                    this.generalDelete.setText("" + proyectoDelete.getObjetivoGeneral());
                    this.especificosDelete.setText("" + proyectoDelete.getObjetivoEspecifico());
                    this.modDelete.setText("" + proyectoDelete.getModalidad());
                    this.lineaDelete.setText("" + proyectoDelete.getLinea());
                    this.profesoresDelete.setText(proyectoDelete.mostrarProfesores());
                    this.estudiantesDelete.setText(proyectoDelete.mostrarEstudiantes());
                    this.notaDelete.setText("" + proyectoDelete.getNota());

                    JOptionPane.showMessageDialog(this, "DATOS ENCONTRADOS ", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

                }//verificar que el valor sea diferente de nulo
                else {
                    JOptionPane.showMessageDialog(this, "CEDULA NO ENCONTRADA ", "ERROR", JOptionPane.ERROR_MESSAGE);

                }//cedula no  encontrada

            } else {
                JOptionPane.showMessageDialog(this, "CEDULA MAL DIGITADA", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
        } catch (Exception e) {

            System.out.println(e);

        }
    }//GEN-LAST:event_buscarDeleteActionPerformed

    private void idDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idDeleteActionPerformed

    private void nombreUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUpdateActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        Proyecto proyectoUpdate;
        try {

            if (!(this.busIdRead.equals(""))) {

                if (!(controlProyecto.readProyecto(Long.parseLong(this.busIdUpdate.getText())) == null)) {

                    proyectoUpdate = controlProyecto.readProyecto(Long.parseLong(busIdUpdate.getText()));
                    this.idUpdate.setText("" + proyectoUpdate.getId());
                    this.nombreUpdate.setText("" + proyectoUpdate.getNombreProyecto());
                    this.generalUpdate.setText("" + proyectoUpdate.getObjetivoGeneral());
                    this.especificosUpdate.setText("" + proyectoUpdate.getObjetivoEspecifico());
                    this.notaUpdate.setText("" + proyectoUpdate.getNota());

                    JOptionPane.showMessageDialog(this, "DATOS ENCONTRADOS ", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

                }//verificar que el valor sea diferente de nulo
                else {
                    JOptionPane.showMessageDialog(this, "CEDULA NO ENCONTRADA ", "ERROR", JOptionPane.ERROR_MESSAGE);

                }//cedula no  encontrada

            } else {
                JOptionPane.showMessageDialog(this, "CEDULA MAL DIGITADA", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
        } catch (Exception e) {

            System.out.println(e);

        }
    }//GEN-LAST:event_buscarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed

        Proyecto actualizacion = new Proyecto();
        actualizacion.setId(Long.parseLong(this.idUpdate.getText()));
        actualizacion.setNombreProyecto(this.nombreUpdate.getText());
        actualizacion.setObjetivoGeneral(generalUpdate.getText());
        actualizacion.setObjetivoEspecifico(this.especificosUpdate.getText());

        actualizacion.setNota(Double.parseDouble(this.notaUpdate.getText()));

        if (controlProyecto.updateProyecto(actualizacion)) {
            JOptionPane.showMessageDialog(this, "DATOS ACTUALIZADOS", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "DATOS NO ACTUALIZADOS", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_actualizarActionPerformed

    private void vDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vDeleteActionPerformed
        if (!(this.idDelete.getText().equals(""))) {
            int a = JOptionPane.showConfirmDialog(this, "¿QUIERES ELIMINAR EL REGISTRO?", "VENTANA CONFIRMACIÓN", JOptionPane.YES_NO_OPTION);
            if (a == 0) {
                if (controlProyecto.deleteProyecto(Long.parseLong(idDelete.getText()))) {
                    JOptionPane.showMessageDialog(this, "INFORMACIÓN BORRADA", "INFORMACIÓN", JOptionPane.WARNING_MESSAGE);
                    this.idDelete.setText("");
                    this.nombreDelete.setText("");
                    this.generalDelete.setText("");
                    this.especificosDelete.setText("");
                    this.modDelete.setText("");
                    this.lineaDelete.setText("");
                    this.profesoresDelete.setText("");
                    this.estudiantesDelete.setText("");
                    this.notaDelete.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "NO SE ELIMINO", "ERROR", JOptionPane.ERROR_MESSAGE);
                    this.idDelete.setText("");
                    this.nombreDelete.setText("");
                    this.generalDelete.setText("");
                    this.especificosDelete.setText("");
                    this.modDelete.setText("");
                    this.lineaDelete.setText("");
                    this.profesoresDelete.setText("");
                    this.estudiantesDelete.setText("");
                    this.notaDelete.setText("");
                }

            } else {
                this.idDelete.setText("");
                this.nombreDelete.setText("");
                this.generalDelete.setText("");
                this.especificosDelete.setText("");
                this.modDelete.setText("");
                this.lineaDelete.setText("");
                this.profesoresDelete.setText("");
                this.estudiantesDelete.setText("");
                this.notaDelete.setText("");
            }

        } else {
            JOptionPane.showMessageDialog(this, "INFORMACIÓN VACÍA", "ERROR", JOptionPane.ERROR_MESSAGE);
            this.idDelete.setText("");
            this.nombreDelete.setText("");
            this.generalDelete.setText("");
            this.especificosDelete.setText("");
            this.modDelete.setText("");
            this.lineaDelete.setText("");
            this.profesoresDelete.setText("");
            this.estudiantesDelete.setText("");
            this.notaDelete.setText("");
        }
    }//GEN-LAST:event_vDeleteActionPerformed

    private void idCreateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idCreateKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_idCreateKeyTyped

    private void idUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idUpdateKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_idUpdateKeyTyped

    private void busIdUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busIdUpdateKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_busIdUpdateKeyTyped

    private void busIdReadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busIdReadKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_busIdReadKeyTyped

    private void busIdDeleteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busIdDeleteKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_busIdDeleteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Create;
    private javax.swing.JPanel Delete;
    private javax.swing.JPanel Read;
    private javax.swing.JPanel Update;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton botonEstudiante;
    private javax.swing.JButton botonProfesor;
    private javax.swing.JTextField busIdDelete;
    private javax.swing.JTextField busIdRead;
    private javax.swing.JTextField busIdUpdate;
    private javax.swing.JButton buscar;
    private javax.swing.JButton buscarDelete;
    private javax.swing.JButton buscarRead;
    private javax.swing.JComboBox<String> comboLineas;
    private javax.swing.JComboBox<String> comboModalidades;
    private javax.swing.JTextArea especificoCreate;
    private javax.swing.JTextArea especificosDelete;
    private javax.swing.JTextArea especificosRead;
    private javax.swing.JTextArea especificosUpdate;
    private javax.swing.JTextArea estudiantesDelete;
    private javax.swing.JTextArea estudiantesRead;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JLabel fondo4;
    private javax.swing.JTextArea generalCreate;
    private javax.swing.JTextArea generalDelete;
    private javax.swing.JTextArea generalRead;
    private javax.swing.JTextArea generalUpdate;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField idCreate;
    private javax.swing.JTextField idDelete;
    private javax.swing.JTextField idUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField lineaDelete;
    private javax.swing.JTextField lineaRead;
    private javax.swing.JComboBox<String> lineasInvestigacionCreate;
    private javax.swing.JTextField modDelete;
    private javax.swing.JTextField modRead;
    private javax.swing.JComboBox<String> modalidadesCreate;
    private javax.swing.JTextField nombreCreate;
    private javax.swing.JTextField nombreDelete;
    private javax.swing.JTextField nombreRead;
    private javax.swing.JTextField nombreUpdate;
    private javax.swing.JTextField notaCreate;
    private javax.swing.JTextField notaDelete;
    private javax.swing.JTextField notaUpdate;
    private javax.swing.JTextArea profesRead;
    private javax.swing.JTextArea profesoresDelete;
    private javax.swing.JButton vDelete;
    // End of variables declaration//GEN-END:variables
}
