/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorPersona;
import controlador.ControladorProyecto;
import java.awt.Image;
import static java.awt.SystemColor.control;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Profesor;
import modelo.Proyecto;

/**
 *
 * @author magq2
 */
public class V_VincularProfesor extends javax.swing.JFrame {
ControladorPersona controlPersona = new ControladorPersona();
ControladorProyecto controlP = new ControladorProyecto();
Proyecto proy = null;
    /**
     * Creates new form c_VincularProfesor
     */
    public V_VincularProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        apellidosText = new javax.swing.JLabel();
        añoUpdate = new javax.swing.JTextField();
        fechaText = new javax.swing.JLabel();
        cedUpdate = new javax.swing.JTextField();
        emailUpdate = new javax.swing.JTextField();
        apelliUpdate = new javax.swing.JTextField();
        nomUpdate = new javax.swing.JTextField();
        emailText = new javax.swing.JLabel();
        nombreText = new javax.swing.JLabel();
        cedulaText = new javax.swing.JLabel();
        diaUpdate = new javax.swing.JTextField();
        mesUpdate = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        busCedUpdate = new javax.swing.JTextField();
        buscarUpdate = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        actualizar = new javax.swing.JButton();
        comboBoxP = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fondo1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProfesores = new javax.swing.JTextArea();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vincular Profesor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        apellidosText.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        apellidosText.setForeground(new java.awt.Color(255, 255, 255));
        apellidosText.setText("Apellidos:");
        jPanel1.add(apellidosText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        añoUpdate.setEditable(false);
        jPanel1.add(añoUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 70, 30));

        fechaText.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        fechaText.setForeground(new java.awt.Color(255, 255, 255));
        fechaText.setText("Fecha de Nacimiento:");
        jPanel1.add(fechaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        cedUpdate.setEditable(false);
        cedUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedUpdateKeyTyped(evt);
            }
        });
        jPanel1.add(cedUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 220, 30));

        emailUpdate.setEditable(false);
        jPanel1.add(emailUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 220, 30));

        apelliUpdate.setEditable(false);
        jPanel1.add(apelliUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 220, 30));

        nomUpdate.setEditable(false);
        jPanel1.add(nomUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 220, 30));

        emailText.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        emailText.setForeground(new java.awt.Color(255, 255, 255));
        emailText.setText("Email:");
        jPanel1.add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        nombreText.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        nombreText.setForeground(new java.awt.Color(255, 255, 255));
        nombreText.setText("Nombre:");
        jPanel1.add(nombreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 20));

        cedulaText.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cedulaText.setForeground(new java.awt.Color(255, 255, 255));
        cedulaText.setText("Cedula:");
        jPanel1.add(cedulaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        diaUpdate.setEditable(false);
        jPanel1.add(diaUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 40, 30));

        mesUpdate.setEditable(false);
        jPanel1.add(mesUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 40, 30));

        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Dia");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Mes");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        jLabel26.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("año");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 290, -1));

        busCedUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                busCedUpdateKeyTyped(evt);
            }
        });
        jPanel1.add(busCedUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, 30));

        buscarUpdate.setText("Buscar");
        buscarUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(buscarUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel27.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("VINCULAR  PROFESOR");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Digite una  cedula(*)");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        actualizar.setText("VINCULAR");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        comboBoxP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ninguno" }));
        comboBoxP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 30));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Proyecto a asociar (*)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        jButton1.setText("DESVINCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, -1, -1));
        jPanel1.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 620));

        jTabbedPane1.addTab("Vincular profesor", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaProfesores.setColumns(20);
        listaProfesores.setRows(5);
        jScrollPane1.setViewportView(listaProfesores);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 570));
        jPanel2.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 620));

        jTabbedPane1.addTab("Registro  de profesores", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUpdateActionPerformed
        Profesor profeUpdate;
        
        if (!(this.busCedUpdate.getText().equals(""))) {

            if (!(controlPersona.readPersona(Long.parseLong(busCedUpdate.getText())) == null)) {

                profeUpdate = (Profesor) controlPersona.readPersona(Long.parseLong(busCedUpdate.getText()));

                this.cedUpdate.setText("" + profeUpdate.getCedula());
                this.nomUpdate.setText("" + profeUpdate.getNombre());
                this.apelliUpdate.setText("" + profeUpdate.getApellidos());
                this.emailUpdate.setText("" + profeUpdate.getEmail());
                this.añoUpdate.setText("" + profeUpdate.getFechaNacimiento().getYear());
                this.mesUpdate.setText("" + profeUpdate.getFechaNacimiento().getMonthValue());
                this.diaUpdate.setText("" + profeUpdate.getFechaNacimiento().getDayOfMonth());

                JOptionPane.showMessageDialog(this, "DATOS ENCONTRADOS ", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

            }
            else {
                JOptionPane.showMessageDialog(this, "CEDULA NO ENCONTRADA ", "ERROR", JOptionPane.ERROR_MESSAGE);
                this.cedUpdate.setText("");
                this.nomUpdate.setText("");
                this.apelliUpdate.setText("");
                this.emailUpdate.setText("");
                this.añoUpdate.setText("");
                this.mesUpdate.setText("");
                this.diaUpdate.setText("");

            }//cedula no  encontrada

        } else {
            JOptionPane.showMessageDialog(this, "CEDULA MAL DIGITADA", "ERROR", JOptionPane.ERROR_MESSAGE);
            this.cedUpdate.setText("");
            this.nomUpdate.setText("");
            this.apelliUpdate.setText("");
            this.emailUpdate.setText("");
            this.añoUpdate.setText("");
            this.mesUpdate.setText("");
            this.diaUpdate.setText("");

        }
    }//GEN-LAST:event_buscarUpdateActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
  Profesor vincular = new Profesor();
 Long cedDes=Long.parseLong(this.cedUpdate.getText());
        this.proy= (Proyecto) controlP.readProyecto(Long.parseLong((String) comboBoxP.getSelectedItem()));
        vincular.setCedula(Long.parseLong(this.cedUpdate.getText()));
        vincular.setNombre(this.nomUpdate.getText());
        vincular.setApellidos(this.apelliUpdate.getText());
        vincular.setEmail(this.emailUpdate.getText());
        vincular.setFechaNacimiento(LocalDate.of(Integer.parseInt(this.añoUpdate.getText()), Integer.parseInt(this.mesUpdate.getText()), Integer.parseInt(this.diaUpdate.getText())));

        if (controlP.vincularProfesor(proy, cedDes, vincular)) {
            JOptionPane.showMessageDialog(this, "PROFESOR VINCULADO", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

            this.cedUpdate.setText("");
            this.nomUpdate.setText("");
            this.apelliUpdate.setText("");
            this.emailUpdate.setText("");
            this.añoUpdate.setText("");
            this.mesUpdate.setText("");
            this.diaUpdate.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "PROCESO NO REALIZADO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void comboBoxPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Long cedDes=Long.parseLong(this.cedUpdate.getText());
        this.proy= (Proyecto) controlP.readProyecto(Long.parseLong((String) comboBoxP.getSelectedItem()));
        if (controlP.desvincularProfesor(proy, cedDes)==true) {
            JOptionPane.showMessageDialog(this, "PROFESOR DESVINCULADO", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

            this.cedUpdate.setText("");
            this.nomUpdate.setText("");
            this.apelliUpdate.setText("");
            this.emailUpdate.setText("");
            this.añoUpdate.setText("");
            this.mesUpdate.setText("");
            this.diaUpdate.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "PROCESO NO REALIZADO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
V_Menu menu=new V_Menu();
menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
      
        ArrayList <Proyecto>proyectos=controlP.enviarProyectos();
        comboBoxP.removeAllItems();
        for (int i = 0; i < proyectos.size(); i++) {
         comboBoxP.addItem(""+proyectos.get(i).getId()); 
            
        }
        
        listaProfesores.setText(controlPersona.enviarProfesores());
       
                                           
        //FONDOS
        //instancio la imagen que esta guardada en el Packages
        Image fondoProfe = new ImageIcon(getClass().getResource("/imagenes/fondoprofesor.jpg")).getImage();

        //le asigno un tamaño de la imagen 
        Image FondoProfe = fondoProfe.getScaledInstance(this.fondo1.getWidth(), this.fondo1.getHeight(), Image.SCALE_SMOOTH);//le asigno  los valores realaes de el  boton

        ImageIcon icono = new ImageIcon(FondoProfe);

        //asigno la imagen al  boton
        this.fondo1.setIcon(icono);
        this.fondo2.setIcon(icono);
       
        
        
       
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void busCedUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busCedUpdateKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_busCedUpdateKeyTyped

    private void cedUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedUpdateKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_cedUpdateKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_VincularProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_VincularProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_VincularProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_VincularProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_VincularProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField apelliUpdate;
    private javax.swing.JLabel apellidosText;
    private javax.swing.JTextField añoUpdate;
    private javax.swing.JTextField busCedUpdate;
    private javax.swing.JButton buscarUpdate;
    private javax.swing.JTextField cedUpdate;
    private javax.swing.JLabel cedulaText;
    private javax.swing.JComboBox<String> comboBoxP;
    private javax.swing.JTextField diaUpdate;
    private javax.swing.JLabel emailText;
    private javax.swing.JTextField emailUpdate;
    private javax.swing.JLabel fechaText;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea listaProfesores;
    private javax.swing.JTextField mesUpdate;
    private javax.swing.JTextField nomUpdate;
    private javax.swing.JLabel nombreText;
    // End of variables declaration//GEN-END:variables
}
