/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorPersona;
import controlador.ControladorProyecto;
import java.awt.Image;
import static java.awt.SystemColor.control;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Estudiante;
import modelo.Proyecto;

/**
 *
 * @author magq2
 */
public class V_VincularEstudiante extends javax.swing.JFrame {

    ControladorPersona control = new ControladorPersona();
    ControladorProyecto controlP = new ControladorProyecto();
    Proyecto proy = null;

    /**
     * Creates new form v_VincularEstudiante
     */
    public V_VincularEstudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        apellidosText = new javax.swing.JLabel();
        añoUpdate = new javax.swing.JTextField();
        fechaText = new javax.swing.JLabel();
        cedUpdate = new javax.swing.JTextField();
        emailUpdate = new javax.swing.JTextField();
        celularUpdate = new javax.swing.JTextField();
        nomUpdate = new javax.swing.JTextField();
        emailText = new javax.swing.JLabel();
        nombreText = new javax.swing.JLabel();
        cedulaText = new javax.swing.JLabel();
        diaUpdate = new javax.swing.JTextField();
        mesUpdate = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        busCedUpdate = new javax.swing.JTextField();
        buscarUpdate = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        botonDes = new javax.swing.JButton();
        comboBoxP = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        botonVin = new javax.swing.JButton();
        fondo1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEstudiantes = new javax.swing.JTextArea();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vincular estudiante");
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        apellidosText.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        apellidosText.setForeground(new java.awt.Color(255, 255, 255));
        apellidosText.setText("Celular:");
        jPanel1.add(apellidosText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        añoUpdate.setEditable(false);
        añoUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                añoUpdateKeyTyped(evt);
            }
        });
        jPanel1.add(añoUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 70, 30));

        fechaText.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        fechaText.setForeground(new java.awt.Color(255, 255, 255));
        fechaText.setText("Fecha de Nacimiento:");
        jPanel1.add(fechaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        cedUpdate.setEditable(false);
        cedUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedUpdateKeyTyped(evt);
            }
        });
        jPanel1.add(cedUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 220, 30));

        emailUpdate.setEditable(false);
        jPanel1.add(emailUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 220, 30));

        celularUpdate.setEditable(false);
        jPanel1.add(celularUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 220, 30));

        nomUpdate.setEditable(false);
        jPanel1.add(nomUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 220, 30));

        emailText.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        emailText.setForeground(new java.awt.Color(255, 255, 255));
        emailText.setText("Email:");
        jPanel1.add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        nombreText.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        nombreText.setForeground(new java.awt.Color(255, 255, 255));
        nombreText.setText("Nombre:");
        jPanel1.add(nombreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 20));

        cedulaText.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cedulaText.setForeground(new java.awt.Color(255, 255, 255));
        cedulaText.setText("Cedula:");
        jPanel1.add(cedulaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        diaUpdate.setEditable(false);
        diaUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diaUpdateKeyTyped(evt);
            }
        });
        jPanel1.add(diaUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 40, 30));

        mesUpdate.setEditable(false);
        mesUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mesUpdateKeyTyped(evt);
            }
        });
        jPanel1.add(mesUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 40, 30));

        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Dia");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Mes");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        jLabel26.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("año");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 290, -1));

        busCedUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                busCedUpdateKeyTyped(evt);
            }
        });
        jPanel1.add(busCedUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, 30));

        buscarUpdate.setText("Buscar");
        buscarUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(buscarUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel27.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("VINCULAR  ESTUDIANTE");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Digite una  cedula(*)");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        botonDes.setText("DESVINCULAR");
        botonDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDesActionPerformed(evt);
            }
        });
        jPanel1.add(botonDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, -1, -1));

        comboBoxP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ninguno" }));
        comboBoxP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 30));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Proyecto a asociar (*)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        botonVin.setText("VINCULAR");
        botonVin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVinActionPerformed(evt);
            }
        });
        jPanel1.add(botonVin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));
        jPanel1.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 700));

        jTabbedPane1.addTab("Vincular estudiante", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaEstudiantes.setColumns(20);
        listaEstudiantes.setRows(5);
        jScrollPane1.setViewportView(listaEstudiantes);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 25, 284, 578));
        jPanel2.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 630));

        jTabbedPane1.addTab("Estudiantes registrados", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUpdateActionPerformed
        Estudiante estudeUpdate;

        if (!(this.busCedUpdate.getText().equals(""))) {

            if (!(control.readPersona(Long.parseLong(busCedUpdate.getText())) == null)) {

                estudeUpdate = (Estudiante) control.readPersona(Long.parseLong(busCedUpdate.getText()));

                this.cedUpdate.setText("" + estudeUpdate.getCedula());
                this.nomUpdate.setText("" + estudeUpdate.getNombre());
                this.celularUpdate.setText("" + estudeUpdate.getCelular());
                this.emailUpdate.setText("" + estudeUpdate.getEmail());
                this.añoUpdate.setText("" + estudeUpdate.getFechaNacimiento().getYear());
                this.mesUpdate.setText("" + estudeUpdate.getFechaNacimiento().getMonthValue());
                this.diaUpdate.setText("" + estudeUpdate.getFechaNacimiento().getDayOfMonth());

                JOptionPane.showMessageDialog(this, "DATOS ENCONTRADOS ", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(this, "CEDULA NO ENCONTRADA ", "ERROR", JOptionPane.ERROR_MESSAGE);
                this.cedUpdate.setText("");
                this.nomUpdate.setText("");
                this.celularUpdate.setText("");
                this.emailUpdate.setText("");
                this.añoUpdate.setText("");
                this.mesUpdate.setText("");
                this.diaUpdate.setText("");

            }//cedula no  encontrada

        } else {
            JOptionPane.showMessageDialog(this, "CEDULA MAL DIGITADA", "ERROR", JOptionPane.ERROR_MESSAGE);
            this.cedUpdate.setText("");
            this.nomUpdate.setText("");
            this.celularUpdate.setText("");
            this.emailUpdate.setText("");
            this.añoUpdate.setText("");
            this.mesUpdate.setText("");
            this.diaUpdate.setText("");

        }
    }//GEN-LAST:event_buscarUpdateActionPerformed

    private void botonDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDesActionPerformed

        Long cedDes = Long.parseLong(this.cedUpdate.getText());
        this.proy = (Proyecto) controlP.readProyecto(Long.parseLong((String) comboBoxP.getSelectedItem()));
        if (controlP.desvincularEstudiante(proy, cedDes) == true) {
            JOptionPane.showMessageDialog(this, "ESTUDIANTE DESVINCULADO", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

            this.cedUpdate.setText("");
            this.nomUpdate.setText("");
            this.celularUpdate.setText("");
            this.emailUpdate.setText("");
            this.añoUpdate.setText("");
            this.mesUpdate.setText("");
            this.diaUpdate.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "PROCESO NO REALIZADO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonDesActionPerformed

    private void comboBoxPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxPActionPerformed

    private void botonVinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVinActionPerformed
        Estudiante vincular = new Estudiante();
        Long cedDes = Long.parseLong(this.cedUpdate.getText());
        this.proy = (Proyecto) controlP.readProyecto(Long.parseLong((String) comboBoxP.getSelectedItem()));
        vincular.setCedula(Long.parseLong(this.cedUpdate.getText()));
        vincular.setNombre(this.nomUpdate.getText());
        vincular.setCelular(Long.parseLong(this.celularUpdate.getText()));
        vincular.setEmail(this.emailUpdate.getText());
        vincular.setFechaNacimiento(LocalDate.of(Integer.parseInt(this.añoUpdate.getText()), Integer.parseInt(this.mesUpdate.getText()), Integer.parseInt(this.diaUpdate.getText())));

        if (controlP.vincularEstudiante(proy, cedDes, vincular) == true) {
            JOptionPane.showMessageDialog(this, "ESTUDIANTE VINCULADO", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

            this.cedUpdate.setText("");
            this.nomUpdate.setText("");
            this.celularUpdate.setText("");
            this.emailUpdate.setText("");
            this.añoUpdate.setText("");
            this.mesUpdate.setText("");
            this.diaUpdate.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "PROCESO NO REALIZADO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonVinActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        V_Menu menu = new V_Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
       ArrayList <Proyecto>proyectos=controlP.enviarProyectos();
       comboBoxP.removeAllItems();
        for (int i = 0; i < proyectos.size(); i++) {
         comboBoxP.addItem(""+proyectos.get(i).getId()); 
            
        }
        listaEstudiantes.setText(control.enviarEstudiantes());
        
        //FONDOS
        //instancio la imagen que esta guardada en el Packages
        Image fondoProfe = new ImageIcon(getClass().getResource("/imagenes/fondoestudiante.jpg")).getImage();

        //le asigno un tamaño de la imagen 
        Image FondoProfe = fondoProfe.getScaledInstance(this.fondo1.getWidth(), this.fondo1.getHeight(), Image.SCALE_SMOOTH);//le asigno  los valores realaes de el  boton

        ImageIcon icono = new ImageIcon(FondoProfe);

        //asigno la imagen al  boton
        this.fondo1.setIcon(icono);
        this.fondo2.setIcon(icono);
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void busCedUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busCedUpdateKeyTyped
     char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_busCedUpdateKeyTyped

    private void cedUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedUpdateKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_cedUpdateKeyTyped

    private void diaUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diaUpdateKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_diaUpdateKeyTyped

    private void mesUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesUpdateKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_mesUpdateKeyTyped

    private void añoUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_añoUpdateKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_añoUpdateKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_VincularEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_VincularEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_VincularEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_VincularEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_VincularEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidosText;
    private javax.swing.JTextField añoUpdate;
    private javax.swing.JButton botonDes;
    private javax.swing.JButton botonVin;
    private javax.swing.JTextField busCedUpdate;
    private javax.swing.JButton buscarUpdate;
    private javax.swing.JTextField cedUpdate;
    private javax.swing.JLabel cedulaText;
    private javax.swing.JTextField celularUpdate;
    private javax.swing.JComboBox<String> comboBoxP;
    private javax.swing.JTextField diaUpdate;
    private javax.swing.JLabel emailText;
    private javax.swing.JTextField emailUpdate;
    private javax.swing.JLabel fechaText;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea listaEstudiantes;
    private javax.swing.JTextField mesUpdate;
    private javax.swing.JTextField nomUpdate;
    private javax.swing.JLabel nombreText;
    // End of variables declaration//GEN-END:variables
}
